name: Build

on:
  push:
    branches:
      - main  # Trigger only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1  # Optional, for setting up compiler
        with:
          compiler: g++

      - name: Build with make
        run: |
          make clean
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build
          path: bin/build/lim
