name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with make
        run: |
          make clean
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lim-linux
          path: bin/build/lim

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lim-linux
          path: release/

      - name: Compress
        run: |
          cd release
          zip -r lim-linux.zip lim-linux

      - name: List
        run: |
          tree release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
            ### Linux
            ``` console
            unzip lim-linux.zip
            cd lim-linux
            chmod +x lim
            ```
          files: release/lim-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
