name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lim-build  # Name of the uploaded artifact
          path: release/   # Download location within the workflow

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
          files: release/lim  # Path to the downloaded binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
